rm(list=ls())
setwd("C:\\Users\\bertj\\OneDrive\\Documenten\\GitHub\\SMWA_Performance\\data")

load("First_Scrape9_03.Rdata")
tweets1 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
#load("Scrape_09_03.Rdata")
#tweets2 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])   # there is something wrong with this file
load("Scrape1_10_03.Rdata")
tweets3 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_13_03.Rdata")
tweets4 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_14_03.Rdata")
tweets5 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_15_03.Rdata")
tweets6 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_16_03.Rdata")
tweets7 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape2_16_03.Rdata")
tweets8 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape3_16_03.Rdata")
tweets9 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape4_16_03.Rdata")
tweets10 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape5_16_03.Rdata")
tweets11 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape5_03.Rdata")
tweets12 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape3_22_03.Rdata")
tweets13 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape3_19_03.Rdata")
tweets14 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape3_18_03.Rdata")
tweets15 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape2_22_03.Rdata")
tweets16 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape2_19_03.Rdata")
tweets17 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape2_18_03.Rdata")
tweets18 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_22_03.Rdata")
tweets19 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape1_19_03.Rdata")
tweets20 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape_17_03_tweets2.Rdata")
tweets21 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape_17_03.Rdata")
tweets22 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape_18_03.Rdata")
tweets23 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])
load("Scrape2_22_03.Rdata")
tweets24 <- as.data.frame(tweets[, c("user_id", "created_at", "text")])



all_tweets <- rbind(tweets1, tweets3, tweets4, tweets5, tweets6, tweets7, tweets8, tweets9, tweets10, tweets11, tweets12, tweets13, tweets14,
                    tweets15, tweets16, tweets17, tweets18, tweets19, tweets20, tweets21, tweets22, tweets23, tweets24)
colnames(all_tweets) <- c("user_id", "date", "text")

class(all_tweets)

sum(duplicated(all_tweets))
all_tweets <- all_tweets[!duplicated(all_tweets), ]

save(all_tweets, file = "all_tweets.Rdata")
