---
title: "Basetablecreation"
output: html_notebook
---


```{r}
### Basetable creation and splitting ###

set.seed(123)
rm(list = ls())
library(quantmod)

###### Read Data ######
load("C:\\Users\\bertj\\OneDrive\\Documenten\\GitHub\\SMWA_Performance\\data\\All_tweets_all_features.RData")
```

```{r}
# Financial data
load("C:\\Users\\bertj\\OneDrive\\Documenten\\GitHub\\SMWA_Performance\\data\\Financial_Data.RData")
```


```{r}
names(all_tweets)[2] <- "sentiment_by_dictionary"
tweets_agg <- aggregate(cbind(sentiment_by_basic,sentiment_weighted_mixed,sentiment_avg_mean, tweets_train$sentiment_by_dictionary,Topic_1,Topic_2) ~ all_tweets$date, all_tweets, mean)
colnames(tweets_agg) <- colnames(all_tweets)

plot(tweets_agg$date, tweets_agg$sentiment_by_dictionary,type = "o", col = "red", xlab = "Date", ylab = "Average Sentiment per Hour", main = "Sentiment", ylim = c(-2,2.1))

legend("bottomleft", legend=c("Dictionary", "Avg_Mean", "Basic","Weighted_mixed"), col=c("red", "blue", "green", "orange"), lty=1, cex=0.8)

lines(tweets_agg$date, tweets_agg$sentiment_avg_mean, type = "o", col = "blue")

lines(tweets_agg$date, tweets_agg$sentiment_by_basic, type = "o", col = "green")

lines(tweets_agg$date, tweets_agg$sentiment_weighted_mixed, type = "o", col = "orange")

```


```{r}
#plot only where topic 2 is mentioned 

plot(tweets_agg$date, tweets_agg$Topic_1,type = "o", col = "red", xlab = "Date", ylab = "average topics occurence", main = "Topic Occurence", ylim = c(0,2))

legend("topright", legend=c("Topic1: coffee experiences", "Topic2: Ukraine conflict"), col=c("red", "blue"), lty=1, cex=0.8)

lines(tweets_agg$date, tweets_agg$Topic_2, type = "o", col = "blue")



```
Let's look at the sentiment of tweets regarding topic 2 
```{r}
tweets_russia <- tweets_agg[tweets_agg$Topic_2>0.2,]


plot(tweets_russia$date, tweets_russia$sentiment_by_dictionary,type = "o", col = "red", xlab = "Date", ylab = "Average Sentiment per Hour (using dictionary)", main = "Sentiment of tweets related to Russia", ylim = c(-0.3,0.3))
abline(h = 0)


```

Let's look at the sentiment of tweets regarding topic 1
```{r}
tweets_coffee <- tweets_agg[tweets_agg$Topic_1>0.5,]
tweets_coffee

plot(tweets_coffee$date, tweets_coffee$sentiment_by_dictionary,type = "o", col = "green", xlab = "Date", ylab = "Average Sentiment per Hour (using dictionary)", main = "Sentiment of tweets related to coffee", ylim = c(-0.3,0.))
abline(h = 0)
```





```{r}
# Clean tweet data
all_tweets <- subset(all_tweets, select = -c(text, user_id))
names(all_tweets)[2] <- "sentiment_by_dictionary"

# Splitting in train and test set
test_dates <- sample(unique(all_tweets$date), length(unique(all_tweets$date))*0.2)
dates <- unique(all_tweets$date)
train_dates <- dates[!(dates %in% test_dates)]

tweets_test <- all_tweets[all_tweets$date %in% test_dates,]
tweets_train <- all_tweets[all_tweets$date %in% train_dates,]

# Scale 
num.cols <- sapply(all_tweets, is.numeric)

# apply on training set
mean_train <- colMeans(tweets_train[, num.cols])
sd_train <- sapply(tweets_train[, num.cols], sd)
#tweets_train[, num.cols] <- scale(tweets_train[, num.cols], center = mean_train, scale = sd_train)
tweets_train[, num.cols] <- scale(tweets_train[, num.cols], center = TRUE, scale = TRUE)

# apply on test set
tweets_test[, num.cols] <- scale(tweets_test[, num.cols], center = mean_train, scale = sd_train)


```





```{r}
# aggregate
tweets_train_agg <- aggregate(cbind(sentiment_by_basic,sentiment_weighted_mixed,sentiment_avg_mean, tweets_train$sentiment_by_dictionary,Topic_1,Topic_2) ~ tweets_train$date, tweets_train, mean)

tweets_test_agg <- aggregate(cbind(sentiment_by_basic,sentiment_weighted_mixed,sentiment_avg_mean,sentiment_by_dictionary,Topic_1,Topic_2) ~ tweets_test$date, tweets_test, mean)

# change colnames
colnames(tweets_train_agg) <- colnames(tweets_train)
colnames(tweets_test_agg) <- colnames(tweets_test)
```



```{r}
# Making basetable
basetable_train <- merge(tweets_train_agg,financial_data,by="date")
basetable_test <- merge(tweets_test_agg,financial_data,by="date")
```

```{r}
#impute the missing values  
print(sum(is.na(basetable_train))) #no missing values
print(sum(is.na(basetable_test))) #no missing values
```


```{r}
#scaling the financial data 
basetable_train <- subset(basetable_train, select = -c(bb, macd))
basetable_test <- subset(basetable_test, select = -c(bb, macd))

names(basetable_train[,c(10:13)])

# MinMaxScale sentiments

# apply on training set
mean_train <- colMeans(basetable_train[, c(10:13)])
sd_train <- sapply(basetable_train[, c(10:13)], sd)
#tweets_train[, num.cols] <- scale(tweets_train[, num.cols], center = mean_train, scale = sd_train)
basetable_train[, c(10:13)] <- scale(basetable_train[, c(10:13)], center = TRUE, scale = TRUE)

# apply on test set
basetable_test[, c(10:13)] <- scale(basetable_test[, c(10:13)], center = mean_train, scale = sd_train)


```



```{r}
#No outliers were found, so this is not necessary 
# Handle outliers
# handle_outlier_z <- function(col){
#   col_z <- scale(col)
#   ifelse(abs(col_z)>3,
#          sign(col_z)*3*attr(col_z,"scaled:scale") + attr(col_z,"scaled:center"), col)
# }
# basetable_train[, num.cols] <-  sapply(basetable_train[, num.cols], FUN = handle_outlier_z)
```

```{r} 
#moving the finacial data an hour back, such that we make lagged variables 
basetable_train <- subset(basetable_train, select = -c(close, open, high, low, dividends))
basetable_test <- subset(basetable_test, select = -c(close, open, high, low, dividends))

fin_cols <- c("volume", "ema", "M", "ROC", "rsi")

fin_avg_cols_train <- colMeans(basetable_train[, fin_cols])

for (i in 1:(nrow(basetable_train) - 1)) {
  basetable_train[i, fin_cols] <- basetable_train[i + 1, fin_cols]
}

for (col in fin_cols) {
  basetable_train[nrow(basetable_train), col] <- fin_avg_cols_train[col]
}

for (i in 1:(nrow(basetable_test) - 1)) {
  basetable_test[i, fin_cols] <- basetable_test[i + 1, fin_cols]
}

for (col in fin_cols) {
  basetable_test[nrow(basetable_test), col] <- fin_avg_cols_train[col]
}

```

```{r}
setwd("/Users/konstantinlazarov/Documents/GitHub/SMWA_Performance/data")
save(basetable_train, file = "basetable_train.RData")
save(basetable_test, file = "basetable_test.RData")
```




